version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: "node:12"
    steps:
      - run:
          name: Check Node Version
          command: node --version && npm -v
       - checkout
       - restore_cache:
          key: card-visit-nfc-{{ checksum "package.json" }}
      - run:
            name: Update npm
            command: npm install -g npm
      - run:
         name: Install Dependencies
         command: npm install
      - save_cache:
          key: card-visit-nfc-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build Source
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    docker:
      - image: garland/aws-cli-docker
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Deploy to s3
          command: aws s3 sync build/ s3://card-visit-nfc

workflows:
  build_deploy_product:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
